"""Manim presentation: Coordinates as Linear-Combination Recipes."""
from __future__ import annotations

from manim import (
    BLUE_C, GREEN_C, GREY_B, GREY_D, ORANGE, TEAL_C, WHITE, YELLOW,
    DOWN, LEFT, RIGHT, UP,
    Arrow, Create, FadeIn, FadeOut, Line, MathTex, Matrix, NumberPlane,
    ReplacementTransform, Scene, Text, Transform, VGroup, smooth,
)


class CoordinateLinearCombinationsPresentation(Scene):
    CHAPTER_BANNER = "CHANGE OF BASIS"
    LESSON_TITLE = "Coordinates as Linear-Combination Recipes"

    def _heading(self, text):
        item = Text(text, font_size=27, color=WHITE)
        if item.width > 11.6:
            item.scale_to_fit_width(11.6)
        return item

    def _chrome(self, heading_text):
        banner = Text(self.CHAPTER_BANNER, font_size=22, color=GREY_B, weight="BOLD").to_edge(UP, buff=0.16)
        title = Text(self.LESSON_TITLE, font_size=31, color=YELLOW, weight="BOLD").next_to(banner, DOWN, buff=0.12)
        heading = self._heading(heading_text).next_to(title, DOWN, buff=0.17)
        return banner, title, heading

    def _replace_heading(self, old, text):
        new = self._heading(text).move_to(old)
        self.play(ReplacementTransform(old, new), run_time=0.6)
        return new

    @staticmethod
    def _fit(group):
        if group.width > 11.2:
            group.scale_to_fit_width(11.2)
        if group.height > 4.7:
            group.scale_to_fit_height(4.7)
        group.move_to(DOWN * 0.42)
        return group

    @staticmethod
    def _matrix(entries, scale=0.82, v_buff=0.95):
        return Matrix(entries, v_buff=v_buff, h_buff=1.0).scale(scale)

    @staticmethod
    def _standard_grid(plane):
        lines = VGroup()
        for x_value in range(-1, 7):
            lines.add(Line(
                plane.c2p(x_value, -1), plane.c2p(x_value, 5),
                color=GREY_D, stroke_width=3.0 if x_value == 0 else 1.8,
                stroke_opacity=1.0 if x_value == 0 else 0.82,
            ))
        for y_value in range(-1, 6):
            lines.add(Line(
                plane.c2p(-1, y_value), plane.c2p(6, y_value),
                color=GREY_D, stroke_width=3.0 if y_value == 0 else 1.8,
                stroke_opacity=1.0 if y_value == 0 else 0.82,
            ))
        return lines

    @staticmethod
    def _basis_grid(plane):
        """Grid generated by b1=(1,0), b2=(1,1)."""
        lines = VGroup()
        for first in range(-2, 8):
            lines.add(Line(
                plane.c2p(first - 6, -6), plane.c2p(first + 6, 6),
                color=BLUE_C, stroke_width=3.2 if first == 0 else 1.9,
                stroke_opacity=1.0 if first == 0 else 0.82,
            ))
        for second in range(-5, 7):
            lines.add(Line(
                plane.c2p(-3 + second, second), plane.c2p(7 + second, second),
                color=GREEN_C, stroke_width=3.2 if second == 0 else 1.9,
                stroke_opacity=1.0 if second == 0 else 0.82,
            ))
        return lines

    def construct(self):
        banner, title, heading = self._chrome("How can the same vector have two different coordinate columns?")
        self.play(FadeIn(banner), FadeIn(title), FadeIn(heading))
        opening = self._fit(VGroup(
            MathTex(r"\mathbf v=(3,2)", font_size=68, color=ORANGE),
            Text("A coordinate column is a recipe for building the vector.", font_size=36, color=WHITE),
            Text("Change the building blocks, and the recipe changes—not the vector.", font_size=32, color=YELLOW),
        ).arrange(DOWN, buff=0.55))
        self.play(FadeIn(opening[0])); self.play(FadeIn(opening[1])); self.play(FadeIn(opening[2])); self.wait(1.8)

        heading = self._replace_heading(heading, "First build v from the standard basis vectors.")
        self.play(FadeOut(opening))
        plane = NumberPlane(
            x_range=[-1, 6, 1], y_range=[-1, 5, 1], x_length=7.0, y_length=5.7,
            background_line_style={"stroke_opacity": 0.0},
            axis_config={"stroke_color": WHITE, "stroke_width": 2.6},
        ).shift(LEFT * 2.65 + DOWN * 0.43)
        standard_grid = self._standard_grid(plane)
        basis_grid = self._basis_grid(plane)
        vector = Arrow(plane.c2p(0, 0), plane.c2p(3, 2), buff=0, color=ORANGE, stroke_width=9)
        vector_label = MathTex(r"\mathbf v=(3,2)", font_size=37, color=ORANGE).next_to(vector.get_end(), UP, buff=0.08)
        standard_x = Arrow(plane.c2p(0, 0), plane.c2p(3, 0), buff=0, color=GREEN_C, stroke_width=7)
        standard_y = Arrow(plane.c2p(3, 0), plane.c2p(3, 2), buff=0, color=BLUE_C, stroke_width=7)
        standard_recipe = VGroup(
            MathTex(r"\mathbf v=3\mathbf e_1+2\mathbf e_2", font_size=48),
            VGroup(
                MathTex(r"[\mathbf v]_{\mathcal E}=", font_size=45, color=YELLOW),
                self._matrix([["3"], ["2"]], 0.82),
            ).arrange(RIGHT, buff=0.12),
            Text("three horizontal steps, then two vertical steps", font_size=27, color=WHITE),
        ).arrange(DOWN, buff=0.43).move_to(RIGHT * 3.65 + DOWN * 0.34)
        self.play(Create(plane), Create(standard_grid), FadeIn(vector), FadeIn(vector_label))
        self.play(Create(standard_x), Create(standard_y), run_time=2.0)
        self.play(FadeIn(standard_recipe)); self.wait(1.8)

        heading = self._replace_heading(heading, "Now change the building blocks while the orange vector stays fixed.")
        b1 = Arrow(plane.c2p(0, 0), plane.c2p(1, 0), buff=0, color=GREEN_C, stroke_width=7)
        b2 = Arrow(plane.c2p(0, 0), plane.c2p(1, 1), buff=0, color=BLUE_C, stroke_width=7)
        b1_label = MathTex(r"\mathbf b_1=(1,0)", font_size=31, color=GREEN_C).next_to(b1.get_end(), DOWN, buff=0.09)
        b2_label = MathTex(r"\mathbf b_2=(1,1)", font_size=31, color=BLUE_C).next_to(b2.get_end(), UP, buff=0.09)
        basis_first = Arrow(plane.c2p(0, 0), plane.c2p(1, 0), buff=0, color=GREEN_C, stroke_width=7)
        basis_second = Arrow(plane.c2p(1, 0), plane.c2p(3, 2), buff=0, color=BLUE_C, stroke_width=7)
        basis_recipe = VGroup(
            MathTex(r"\mathbf v=1\mathbf b_1+2\mathbf b_2", font_size=48),
            VGroup(
                MathTex(r"[\mathbf v]_{\mathcal B}=", font_size=45, color=YELLOW),
                self._matrix([["1"], ["2"]], 0.82),
            ).arrange(RIGHT, buff=0.12),
            Text("one copy of b1, then two copies of b2", font_size=27, color=WHITE),
        ).arrange(DOWN, buff=0.43).move_to(standard_recipe)
        self.play(FadeOut(standard_x), FadeOut(standard_y))
        self.play(
            Transform(standard_grid, basis_grid, rate_func=smooth),
            ReplacementTransform(standard_recipe, basis_recipe),
            FadeIn(b1), FadeIn(b2), FadeIn(b1_label), FadeIn(b2_label),
            run_time=4.0,
        )
        self.play(Create(basis_first), Create(basis_second), run_time=2.0)
        fixed_note = Text("Same endpoint. Same vector. A different coefficient recipe.", font_size=29, color=ORANGE).to_edge(DOWN, buff=0.10)
        self.play(FadeIn(fixed_note)); self.wait(1.8)

        heading = self._replace_heading(heading, "Substitution translates the B-recipe into the standard recipe.")
        self.play(
            FadeOut(plane), FadeOut(standard_grid), FadeOut(vector), FadeOut(vector_label),
            FadeOut(b1), FadeOut(b2), FadeOut(b1_label), FadeOut(b2_label),
            FadeOut(basis_first), FadeOut(basis_second), FadeOut(basis_recipe), FadeOut(fixed_note),
        )
        substitution = self._fit(VGroup(
            MathTex(r"\mathbf b_1=\mathbf e_1,\qquad \mathbf b_2=\mathbf e_1+\mathbf e_2", font_size=48),
            MathTex(r"\mathbf v=1\mathbf b_1+2\mathbf b_2", font_size=51),
            MathTex(r"=1\mathbf e_1+2(\mathbf e_1+\mathbf e_2)", font_size=51),
            MathTex(r"=3\mathbf e_1+2\mathbf e_2", font_size=54, color=YELLOW),
        ).arrange(DOWN, buff=0.28))
        for line in substitution:
            self.play(FadeIn(line))
        self.wait(1.8)

        heading = self._replace_heading(heading, "Each B-basis vector has its own standard-coordinate recipe.")
        self.play(FadeOut(substitution))
        first_column = VGroup(
            MathTex(r"[\mathbf b_1]_{\mathcal E}=", font_size=46),
            self._matrix([["1"], ["0"]], 0.84),
        ).arrange(RIGHT, buff=0.12)
        second_column = VGroup(
            MathTex(r"[\mathbf b_2]_{\mathcal E}=", font_size=46),
            self._matrix([["1"], ["1"]], 0.84),
        ).arrange(RIGHT, buff=0.12)
        columns = VGroup(first_column, second_column).arrange(RIGHT, buff=0.75)
        assembled = VGroup(
            MathTex(r"P_{\mathcal B}=\big[\,[\mathbf b_1]_{\mathcal E}\ \ [\mathbf b_2]_{\mathcal E}\,\big]=", font_size=43, color=YELLOW),
            self._matrix([["1", "1"], ["0", "1"]], 0.86),
        ).arrange(RIGHT, buff=0.13)
        column_note = Text("The columns store the two substitution recipes.", font_size=31, color=ORANGE)
        column_card = self._fit(VGroup(columns, assembled, column_note).arrange(DOWN, buff=0.50))
        self.play(FadeIn(columns)); self.play(FadeIn(assembled)); self.play(FadeIn(column_note)); self.wait(2.0)

        heading = self._replace_heading(heading, "Matrix multiplication performs both substitutions at once.")
        self.play(FadeOut(column_card))
        multiplication = VGroup(
            self._matrix([["1", "1"], ["0", "1"]], 0.96),
            self._matrix([["1"], ["2"]], 0.96),
            MathTex("=", font_size=58),
            self._matrix([["3"], ["2"]], 0.96),
        ).arrange(RIGHT, buff=0.28)
        labels = VGroup(
            MathTex(r"P_{\mathcal B}", font_size=39, color=TEAL_C),
            MathTex(r"[\mathbf v]_{\mathcal B}", font_size=39, color=YELLOW),
            MathTex(r"[\mathbf v]_{\mathcal E}", font_size=39, color=ORANGE),
        ).arrange(RIGHT, buff=1.05)
        rule = MathTex(r"\boxed{[\mathbf v]_{\mathcal E}=P_{\mathcal B}[\mathbf v]_{\mathcal B}}", font_size=55, color=YELLOW)
        multiplication_card = self._fit(VGroup(multiplication, labels, rule).arrange(DOWN, buff=0.47))
        self.play(FadeIn(multiplication)); self.play(FadeIn(labels)); self.play(FadeIn(rule)); self.wait(2.0)

        heading = self._replace_heading(heading, "The same idea works between any two bases.")
        self.play(FadeOut(multiplication_card))
        general = VGroup(
            MathTex(r"\mathbf b_1=q_{11}\mathbf c_1+q_{21}\mathbf c_2", font_size=45),
            MathTex(r"\mathbf b_2=q_{12}\mathbf c_1+q_{22}\mathbf c_2", font_size=45),
        ).arrange(DOWN, buff=0.18)
        transition = VGroup(
            MathTex(r"Q_{\mathcal C\leftarrow\mathcal B}=\big[\,[\mathbf b_1]_{\mathcal C}\ \ [\mathbf b_2]_{\mathcal C}\,\big]=", font_size=40, color=YELLOW),
            self._matrix([["q_{11}", "q_{12}"], ["q_{21}", "q_{22}"]], 0.82),
        ).arrange(RIGHT, buff=0.12)
        direction = Text("Write each old basis vector as a linear combination of the new basis vectors.", font_size=29, color=ORANGE)
        general_card = self._fit(VGroup(general, transition, direction).arrange(DOWN, buff=0.48))
        self.play(FadeIn(general)); self.play(FadeIn(transition)); self.play(FadeIn(direction)); self.wait(2.1)

        heading = self._replace_heading(heading, "Change of coordinates means rewriting the same linear combination.")
        self.play(FadeOut(general_card))
        final_card = self._fit(VGroup(
            Text("The vector stays fixed.", font_size=34, color=ORANGE),
            Text("The basis changes the available building blocks.", font_size=34, color=WHITE),
            Text("The coordinate column records the new amounts.", font_size=34, color=YELLOW),
            MathTex(r"[\mathbf v]_{\mathcal C}=Q_{\mathcal C\leftarrow\mathcal B}[\mathbf v]_{\mathcal B}", font_size=56, color=YELLOW),
        ).arrange(DOWN, buff=0.44))
        for line in final_card:
            self.play(FadeIn(line))
        self.wait(2.2)
