"""Manim presentation: Why Change Basis?"""
from __future__ import annotations

import numpy as np
from manim import (
    BLUE_C, GREEN_C, GREY_B, GREY_D, ORANGE, WHITE, YELLOW,
    DOWN, LEFT, RIGHT, UP,
    Arrow, Create, FadeIn, FadeOut, Line, MathTex, NumberPlane,
    ReplacementTransform, Scene, Text, VGroup,
)


class WhyChangeBasisPresentation(Scene):
    CHAPTER_BANNER = "CHANGE OF BASIS"
    LESSON_TITLE = "Why Change Basis?"

    def _heading(self, text: str) -> Text:
        item = Text(text, font_size=27, color=WHITE)
        if item.width > 11.6:
            item.scale_to_fit_width(11.6)
        return item

    def _chrome(self, heading_text: str):
        banner = Text(self.CHAPTER_BANNER, font_size=22, color=GREY_B, weight="BOLD")
        banner.to_edge(UP, buff=0.16)
        title = Text(self.LESSON_TITLE, font_size=32, color=YELLOW, weight="BOLD")
        title.next_to(banner, DOWN, buff=0.12)
        heading = self._heading(heading_text)
        heading.next_to(title, DOWN, buff=0.17)
        return banner, title, heading

    def _replace_heading(self, old, text: str):
        new = self._heading(text).move_to(old)
        self.play(ReplacementTransform(old, new), run_time=0.6)
        return new

    @staticmethod
    def _oblique_lattice(plane: NumberPlane) -> VGroup:
        """Lattice generated by b1=(1,1) and b2=(1,-1)."""
        b1 = np.array([1.0, 1.0])
        b2 = np.array([1.0, -1.0])
        lines = VGroup()
        for k in range(-6, 7):
            start = -6 * b1 + k * b2
            end = 6 * b1 + k * b2
            lines.add(Line(plane.c2p(*start), plane.c2p(*end), color=GREY_D, stroke_width=1.25))
            start = k * b1 - 6 * b2
            end = k * b1 + 6 * b2
            lines.add(Line(plane.c2p(*start), plane.c2p(*end), color=GREY_D, stroke_width=1.25))
        return lines

    def construct(self) -> None:
        banner, title, heading = self._chrome(
            "Can one geometric vector have two different coordinate descriptions?"
        )
        self.play(FadeIn(banner), FadeIn(title), FadeIn(heading), run_time=0.8)

        # The graph frame and vector are created once. The vector is never transformed.
        plane = NumberPlane(
            x_range=[-1, 6, 1], y_range=[-3, 5, 1],
            x_length=6.2, y_length=6.2,
            background_line_style={"stroke_color": GREY_D, "stroke_width": 1.2, "stroke_opacity": 0.72},
            axis_config={"stroke_color": GREY_B, "stroke_width": 2.0},
        ).shift(LEFT * 3.05 + DOWN * 0.34)
        vector = Arrow(
            plane.c2p(0, 0), plane.c2p(4, 2),
            buff=0, color=ORANGE, stroke_width=8, max_tip_length_to_length_ratio=0.10,
        )
        vector_label = MathTex(r"\mathbf v", font_size=40, color=ORANGE)
        vector_label.next_to(vector.get_end(), UP + RIGHT, buff=0.10)

        standard_name = Text("Standard basis", font_size=29, color=BLUE_C)
        standard_coords = MathTex(
            r"[\mathbf v]_{\mathcal E}=\begin{bmatrix}4\\2\end{bmatrix}",
            font_size=48, color=WHITE,
        )
        standard_note = Text("four steps right, two steps up", font_size=25, color=GREY_B)
        standard_panel = VGroup(standard_name, standard_coords, standard_note).arrange(DOWN, buff=0.34)
        standard_panel.to_edge(RIGHT, buff=0.62).shift(DOWN * 0.35)

        self.play(Create(plane), run_time=1.0)
        self.play(FadeIn(vector), FadeIn(vector_label), run_time=0.8)
        self.play(FadeIn(standard_panel), run_time=0.8)
        self.wait(1.5)

        # Introduce a second basis without moving the geometric vector.
        heading = self._replace_heading(heading, "Now measure the same vector with two different basis directions.")
        b1 = Arrow(plane.c2p(0, 0), plane.c2p(1, 1), buff=0, color=GREEN_C, stroke_width=6)
        b2 = Arrow(plane.c2p(0, 0), plane.c2p(1, -1), buff=0, color=BLUE_C, stroke_width=6)
        b1_label = MathTex(r"\mathbf b_1", font_size=33, color=GREEN_C).next_to(b1.get_end(), UP, buff=0.08)
        b2_label = MathTex(r"\mathbf b_2", font_size=33, color=BLUE_C).next_to(b2.get_end(), DOWN, buff=0.08)
        basis_definition = MathTex(
            r"\mathcal B=\left(\begin{bmatrix}1\\1\end{bmatrix},"
            r"\begin{bmatrix}1\\-1\end{bmatrix}\right)",
            font_size=39, color=WHITE,
        ).move_to(standard_coords)
        self.play(FadeOut(standard_note), ReplacementTransform(standard_coords, basis_definition))
        self.play(FadeIn(b1), FadeIn(b2), FadeIn(b1_label), FadeIn(b2_label), run_time=0.9)
        self.wait(1.4)

        # Replace only the coordinate grid; the vector remains the same on screen.
        heading = self._replace_heading(heading, "A new basis is a new coordinate language for the same geometry.")
        lattice = self._oblique_lattice(plane)
        basis_name = Text("Basis B", font_size=29, color=GREEN_C).move_to(standard_name)
        self.play(
            FadeOut(plane), FadeIn(lattice),
            ReplacementTransform(standard_name, basis_name),
            run_time=1.4,
        )
        fixed_callout = Text("same arrow, same endpoint", font_size=27, color=ORANGE)
        fixed_callout.next_to(basis_definition, DOWN, buff=0.55)
        self.play(FadeIn(fixed_callout))
        self.wait(1.5)

        # Change the coordinate readout, not the vector.
        heading = self._replace_heading(heading, "The coordinate numbers change because the coordinate language changed.")
        basis_coordinates = MathTex(
            r"\mathbf v=3\mathbf b_1+\mathbf b_2",
            font_size=43, color=WHITE,
        ).move_to(basis_definition)
        coordinate_column = MathTex(
            r"[\mathbf v]_{\mathcal B}=\begin{bmatrix}3\\1\end{bmatrix}",
            font_size=50, color=YELLOW,
        )
        coordinate_column.next_to(basis_coordinates, DOWN, buff=0.52)
        self.play(ReplacementTransform(basis_definition, basis_coordinates), FadeOut(fixed_callout))
        self.play(FadeIn(coordinate_column))
        self.wait(1.7)

        # Final comparison and central idea.
        heading = self._replace_heading(heading, "Coordinates belong to a vector together with a chosen basis.")
        self.play(FadeOut(b1), FadeOut(b2), FadeOut(b1_label), FadeOut(b2_label))
        comparison = VGroup(
            MathTex(r"[\mathbf v]_{\mathcal E}=\begin{bmatrix}4\\2\end{bmatrix}", font_size=43, color=BLUE_C),
            MathTex(r"[\mathbf v]_{\mathcal B}=\begin{bmatrix}3\\1\end{bmatrix}", font_size=43, color=GREEN_C),
        ).arrange(RIGHT, buff=0.75)
        self.play(FadeOut(basis_name), FadeOut(basis_coordinates), FadeOut(coordinate_column))
        coordinate_takeaway = VGroup(
            Text("Only its coordinate", font_size=28, color=YELLOW),
            Text("description changed.", font_size=28, color=YELLOW),
        ).arrange(DOWN, buff=0.08)
        takeaway = VGroup(
            Text("The vector did not change.", font_size=29, color=ORANGE),
            coordinate_takeaway,
        ).arrange(DOWN, buff=0.22)
        final_panel = VGroup(comparison, takeaway).arrange(DOWN, buff=0.38)
        # Constrain the complete panel, rather than only its individual lines.
        # The right-hand content region is about 5.5 units wide and 4.7 high.
        if final_panel.width > 5.35:
            final_panel.scale_to_fit_width(5.35)
        if final_panel.height > 4.55:
            final_panel.scale_to_fit_height(4.55)
        final_panel.move_to(RIGHT * 3.15 + DOWN * 0.38)
        self.play(FadeIn(comparison))
        self.play(FadeIn(takeaway), run_time=0.8)
        self.wait(2.0)
